from pages.checkout_pdp_add_to_cart_page import Checkout_PDP_SPP_No_Size
from pages.checkout_login import Checkout_Login
from pages.checkout_delivery_page import Checkout_Delivery
from pages.checkout_payment_page import Checkout_Payment
from pages.checkout_review_page import Checkout_Review
from pages.login_pages import Login_Page
from pages.shopping_cart_page import Open_Shopping_Cart_Page
from pages.go_back_from_payment_page import Checkout_Go_Back_From_Payment
from pages.go_back_from_review_page import Checkout_Go_Back_From_Review


def test_checkout_as_registered_user(page):

    checkout_pdp = Checkout_PDP_SPP_No_Size(page)
    checkout_login = Checkout_Login(page)
    checkout_delivery = Checkout_Delivery(page)
    checkout_payment = Checkout_Payment(page)
    checkout_review = Checkout_Review(page)
    login_logout = Login_Page(page)
    shopping_cart = Open_Shopping_Cart_Page(page)
    checkout_back_from_payment = Checkout_Go_Back_From_Payment(page)
    checkout_back_from_review =  Checkout_Go_Back_From_Review(page)



    # Case 1.1: Registered User + Premium Delivery (Same Address and Name without Checkbox) + Amex Credit card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 1.2: Registered User + Premium Delivery (Same Address and Name with Checkbox)
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 1.3: Registered User + Premium Delivery (Different Name) + Union Pay Credit card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()



    # Case 2.1: Registered User + Self Collect + Visa Credit card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()



    # Case 3.1: Registered User + Someone else collect + Master Card Credit card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()



    # Case 4.1: Registered User + Premium Deivery + Back to Cart from Review + Change Delivery to Self Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 4.2: Registered User + Premium Deivery + Back to Cart from Payment + Change Delivery to Self Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()



    # Case 5.1: Registered User + Premium Deivery + Back to Cart from Review + Change Delivery to Someone else Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 5.2: Registered User + Premium Deivery + Back to Cart from Payment + Change Delivery to Someone else Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()



    # Case 6.1: Registered User + Self Collect + Back to Cart from Review + Change to Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 6.2: Registered User + Self Collect + Back to Cart from Payment + Change to Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()



    # Case 7.1: Registered User + Someone else Collect + Back to Cart from Review + Change to Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 7.2: Registered User + Someone else Collect + Back to Cart from Payment + Change to Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()



    # Case 8.1 Registered User + Premium Delivery + Back to Delivery from Review + Change to Self Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 8.2 Registered User + Premium Delivery + Back to Delivery from Review + Change to Someone else Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 8.3 Registered User + Self Collect + Back to Delivery from Review + Change to Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 8.4 Registered User + Someone else Collect + Back to Delivery from Review + Change to Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()
    


    # Case 9.1 Registered User + Premium Delivery + Back to Delivery from Payment + Change to Self Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 9.2 Registered User + Premium Delivery + Back to Delivery from Payment + Change to Someone else Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 9.3 Registered User + Self Collect + Back to Delivery from Payment + Change to Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 9.4 Registered User + Someone else Collect + Back to Delivery from Payment + Change to Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()
    


    # Case 10.1 Registered User + Premium Delivery + Back to Payment from Review
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_premium_delivery_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_payment_from_review_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 10.2 Registered User + Self Collect + Back to Payment from Review
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_self_collect_in_store_as_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_payment_from_review_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()

    # Case 10.3 Registered User + Someone else Collect + Back to Payment from Review
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_registered_user()
    checkout_delivery.test_someone_else_collect_in_store_registered()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_payment_from_review_page()
    checkout_payment.test_select_paypal_payment_method()
    checkout_payment.test_select_cards_payment_method()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
    login_logout.test_logout_from_order_confirmation_page()
