from pages.checkout_pdp_add_to_cart_page import Checkout_PDP_SPP_No_Size
from pages.checkout_login import Checkout_Login
from pages.checkout_delivery_page import Checkout_Delivery
from pages.checkout_payment_page import Checkout_Payment
from pages.checkout_review_page import Checkout_Review
from pages.go_back_from_payment_page import Checkout_Go_Back_From_Payment
from pages.go_back_from_review_page import Checkout_Go_Back_From_Review
from pages.shopping_cart_page import Open_Shopping_Cart_Page



def test_checkout_as_guest_user_premium(page):

    checkout_pdp = Checkout_PDP_SPP_No_Size(page)
    checkout_login = Checkout_Login(page)
    checkout_delivery = Checkout_Delivery(page)
    checkout_payment = Checkout_Payment(page)
    checkout_review = Checkout_Review(page)
    checkout_back_from_payment = Checkout_Go_Back_From_Payment(page)
    checkout_back_from_review =  Checkout_Go_Back_From_Review(page)
    shopping_cart = Open_Shopping_Cart_Page(page)


    # Case 1: Premium Delivery + Amex card + Same Billing address
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_guest_user()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_page_refresh()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 2: Premium Delivery + Visa card + Use Delivery address as Billing address
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_page_refresh()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 3: Premium Delivery + Union Pay card + Different Billing address.
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_page_refresh()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 8: Premium Delivery + Master card > From the Payment page, Go back to the Delivery Page > Change delivery method to Self Collect + Discover card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_open_collect_in_store_tab()
    checkout_delivery.test_select_self_collect_checkbox()
    checkout_delivery.test_delivery_date_on_collect_in_store()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 9: Premium Delivery + Master card > From the Payment page, Go back to the Delivery Page > Change delivery method to Someone Else Collect + Discover card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_open_collect_in_store_tab()
    checkout_delivery.test_select_someone_else_collect_checkbox()
    checkout_delivery.test_enter_collector_details_in_store_collect()
    checkout_delivery.test_delivery_date_on_collect_in_store()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 16: Premium Delivery + Discover card > From the Review page, Go back to the Delivery Page > Premium Delivery + Master card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_page_refresh()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 17: Premium Delivery + Discover card > From the Review page, Go back to the Delivery Page > Change delivery method to Self Collect + Master card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_open_collect_in_store_tab()
    checkout_delivery.test_select_self_collect_checkbox()
    checkout_delivery.test_delivery_date_on_collect_in_store()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 18: Premium Delivery + Discover card > From the Review page, Go back to the Delivery Page > Change delivery method to Someone Else Collect + Master card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_open_collect_in_store_tab()
    checkout_delivery.test_select_someone_else_collect_checkbox()
    checkout_delivery.test_enter_collector_details_in_store_collect()
    checkout_delivery.test_delivery_date_on_collect_in_store()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 25: Premium Delivery + Master card > From the Review page, Go back to the Payment Page > Discover card + Use Delivery address as Billing address
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_page_refresh()
    checkout_back_from_review.test_go_back_to_payment_from_review_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 26: Premium Delivery + Discover card > From the Review page, Go back to the Payment Page > Master card + Different Name and Address
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_page_refresh()
    checkout_back_from_review.test_go_back_to_payment_from_review_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 30: Premium Delivery + Discover card > From the Review page, Go back to the Cart Page > Premium Delivery + Master card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_page_refresh()
    checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 31: Premium Delivery + Discover card > From the Review page, Go back to the Cart Page > Change delivery method to Self Collect + Master card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_open_collect_in_store_tab()
    checkout_delivery.test_select_self_collect_checkbox()
    checkout_delivery.test_enter_collector_details_in_store_collect()
    checkout_delivery.test_delivery_date_on_collect_in_store()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 32: Premium Delivery + Discover card > From the Review page, Go back to the Cart Page > Change delivery method to Someone Else Collect + Master card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_open_collect_in_store_tab()
    checkout_delivery.test_select_someone_else_collect_checkbox()
    checkout_delivery.test_enter_collector_details_in_store_collect()
    checkout_delivery.test_delivery_date_on_collect_in_store()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 39: Premium Delivery + Master card > From the Payment page, Go back to the Cart Page > Premium Delivery + Discover card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_review.test_page_refresh()
    checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 40: Premium Delivery + Master card > From the Payment page, Go back to the Cart Page > Change delivery method to Self Collect + Discover card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_open_premium_delivery_tab()
    checkout_delivery.test_enter_user_details_in_premium_delivery()
    checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
    checkout_delivery.test_delivery_date_on_premium_delivery()
    checkout_delivery.test_enter_gift_message()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_open_collect_in_store_tab()
    checkout_delivery.test_select_self_collect_checkbox()
    checkout_delivery.test_enter_collector_details_in_store_collect()
    checkout_delivery.test_delivery_date_on_collect_in_store()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()
