from pages.checkout_pdp_add_to_cart_page import Checkout_PDP_SPP_No_Size
from pages.checkout_login import Checkout_Login
from pages.checkout_delivery_page import Checkout_Delivery
from pages.checkout_payment_page import Checkout_Payment
from pages.checkout_review_page import Checkout_Review
from pages.go_back_from_payment_page import Checkout_Go_Back_From_Payment
from pages.go_back_from_review_page import Checkout_Go_Back_From_Review
from pages.shopping_cart_page import Open_Shopping_Cart_Page
import os
ENV = os.getenv("ENVIRONMENT").upper()
COUNTRY = os.getenv("LOCALE").upper()
REFRESH = os.getenv("PAGE_REFRESH").upper()
TESTING_TYPE = os.getenv("TESTING_TYPE").upper()



def test_checkout_as_guest_user_self_collect(page):

    checkout_pdp = Checkout_PDP_SPP_No_Size(page)
    checkout_login = Checkout_Login(page)
    checkout_delivery = Checkout_Delivery(page)
    checkout_payment = Checkout_Payment(page)
    checkout_review = Checkout_Review(page)
    checkout_back_from_payment = Checkout_Go_Back_From_Payment(page)
    checkout_back_from_review =  Checkout_Go_Back_From_Review(page)
    shopping_cart = Open_Shopping_Cart_Page(page)

    if (COUNTRY == "UK" or COUNTRY == "US" or COUNTRY == "HK") and TESTING_TYPE == "REGRESSION":

            print("----> TEST CASE 1 OF 15")
            # Case 4: Self Collect + Master card + Same Billing Name
            checkout_pdp.test_checkout_spp_no_size_without_engraving()
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_mastercard_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 2 OF 15")
            # Case 5: Self Collect + Master card + Different Billing Name
            checkout_pdp.test_checkout_spp_no_size_without_engraving()
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_mastercard_credit_card_details()
            checkout_payment.test_enter_change_billing_name_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 3 OF 15")
            # Case 10: Self Collect + Union Pay card > From the Payment page, Go back to the Delivery Page > Self Collect + Amex card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 4 OF 15")
            # Case 11: Self Collect + Union Pay card > From the Payment page, Go back to the Delivery Page > Change delivery method to Premium Delivery + Amex card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
            checkout_delivery.test_open_premium_delivery_tab()
            checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
            checkout_delivery.test_delivery_date_on_premium_delivery()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 5 OF 15")
            # Case 12: Self Collect + Union Pay card > From the Payment page, Go back to the Delivery Page > Change delivery method to Someone Else Collect + Amex card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
            checkout_delivery.test_select_someone_else_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_name_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 6 OF 15")
            # Case 19: Self Collect + Amex card > From the Review page, Go back to the Delivery Page > Self Collect + Union Pay card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_review.test_go_back_to_delivery_from_review_page()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 7 OF 15")
            # Case 20: Self Collect + Amex card > From the Review page, Go back to the Delivery Page > Change delivery method to Premium Delivery + Union Pay card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_back_from_review.test_go_back_to_delivery_from_review_page()
            checkout_delivery.test_open_premium_delivery_tab()
            checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
            checkout_delivery.test_delivery_date_on_premium_delivery()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_use_delivery_as_billing_address_checkbox()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 8 OF 15")
            # Case 21: Self Collect + Amex card > From the Review page, Go back to the Delivery Page > Change delivery method to Someone Else Collect + Union Pay card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_back_from_review.test_go_back_to_delivery_from_review_page()
            checkout_delivery.test_select_someone_else_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_enter_change_billing_name_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 9 OF 15")
            # Case 27: Self Collect + Union Pay card > From the Review page, Go back to the Payment Page > Amex card + Same Billing name
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_review.test_go_back_to_payment_from_review_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 10 OF 15")
            # Case 28: Self Collect + Amex card > From the Review page, Go back to the Payment Page > Union Pay card + Different Billing name
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_review.test_go_back_to_payment_from_review_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_name_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 11 OF 15")
            # Case 33: Self Collect + Amex card > From the Review page, Go back to the Cart Page > Self Collect + Union Pay card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
            shopping_cart.test_continue_to_checkout_from_cart()
            if ENV == "QA":
                    checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 12 OF 15")
            # Case 34: Self Collect + Amex card > From the Review page, Go back to the Cart Page > Change delivery method to Premium Delivery + Union Pay card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
            shopping_cart.test_continue_to_checkout_from_cart()
            if ENV == "QA":
                    checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_premium_delivery_tab()
            checkout_delivery.test_enter_user_details_in_premium_delivery()
            checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
            checkout_delivery.test_delivery_date_on_premium_delivery()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_use_delivery_as_billing_address_checkbox()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 13 OF 15")
            # Case 35: Self Collect + Amex card > From the Review page, Go back to the Cart Page > Change delivery method to Someone Else Collect + Union Pay card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
            shopping_cart.test_continue_to_checkout_from_cart()
            if ENV == "QA":
                    checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_select_someone_else_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_enter_change_billing_name_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 14 OF 15")
            # Case 41: Self Collect + Union Pay card > From the Payment page, Go back to the Cart Page > Self Collect + Amex card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
            shopping_cart.test_continue_to_checkout_from_cart()
            if ENV == "QA":
                    checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 15 OF 15")
            # Case 42: Self Collect + Union Pay card > From the Payment page, Go back to the Cart Page > Change delivery method to Premium Delivery + Amex card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
            shopping_cart.test_continue_to_checkout_from_cart()
            if ENV == "QA":
                    checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_premium_delivery_tab()
            checkout_delivery.test_enter_user_details_in_premium_delivery()
            checkout_delivery.test_enter_valid_delivery_address_in_premium_delivery()
            checkout_delivery.test_delivery_date_on_premium_delivery()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_use_delivery_as_billing_address_checkbox()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

    elif (COUNTRY == "UK" or COUNTRY == "US" or COUNTRY == "HK") and TESTING_TYPE == "SMOKE":

            print("----> TEST CASE 1 OF 6")
            # Case 4: Self Collect + Master card + Same Billing Name
            checkout_pdp.test_checkout_spp_no_size_without_engraving()
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_mastercard_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 2 OF 6")
            # Case 10: Self Collect + Union Pay card > From the Payment page, Go back to the Delivery Page > Self Collect + Amex card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 3 OF 6")
            # Case 19: Self Collect + Amex card > From the Review page, Go back to the Delivery Page > Self Collect + Union Pay card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_review.test_go_back_to_delivery_from_review_page()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 4 OF 6")
            # Case 28: Self Collect + Amex card > From the Review page, Go back to the Payment Page > Union Pay card + Different Billing name
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_review.test_go_back_to_payment_from_review_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_name_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 5 OF 6")
            # Case 33: Self Collect + Amex card > From the Review page, Go back to the Cart Page > Self Collect + Union Pay card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
            shopping_cart.test_continue_to_checkout_from_cart()
            if ENV == "QA":
                    checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

            print("----> TEST CASE 6 OF 6")
            # Case 41: Self Collect + Union Pay card > From the Payment page, Go back to the Cart Page > Self Collect + Amex card
            checkout_pdp.test_checkout_spp_no_size_with_engraving()
            checkout_pdp.test_secure_checkout_from_minicart()
            checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_open_collect_in_store_tab()
            checkout_delivery.test_select_self_collect_checkbox()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_union_pay_credit_card_details()
            if REFRESH == "YES":
                    checkout_review.test_page_refresh()
            checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
            shopping_cart.test_continue_to_checkout_from_cart()
            if ENV == "QA":
                    checkout_login.test_checkout_as_guest_user()
            checkout_delivery.test_enter_collector_details_in_store_collect()
            checkout_delivery.test_delivery_date_on_collect_in_store()
            checkout_delivery.test_continue_to_payment_from_delivery_page()
            checkout_payment.test_enter_amex_credit_card_details()
            checkout_payment.test_enter_change_billing_address_details()
            checkout_payment.test_continue_to_review_from_payment_page()
            checkout_review.test_place_an_order_from_order_review_page()

    elif COUNTRY == "FR" or COUNTRY == "TW" or COUNTRY == "MO":
            print(f"[{ENV}-{COUNTRY}] NO CASES RELATED TO THE COLLECT IN STORE TAB..")