from pages.checkout_pdp_add_to_cart_page import Checkout_PDP_SPP_No_Size
from pages.checkout_login import Checkout_Login
from pages.checkout_delivery_page import Checkout_Delivery
from pages.checkout_payment_page import Checkout_Payment
from pages.checkout_review_page import Checkout_Review
from pages.go_back_from_payment_page import Checkout_Go_Back_From_Payment
from pages.go_back_from_review_page import Checkout_Go_Back_From_Review
from pages.shopping_cart_page import Open_Shopping_Cart_Page



def test_checkout_as_guest_user(page):

    checkout_pdp = Checkout_PDP_SPP_No_Size(page)
    checkout_login = Checkout_Login(page)
    checkout_delivery = Checkout_Delivery(page)
    checkout_payment = Checkout_Payment(page)
    checkout_review = Checkout_Review(page)
    checkout_back_from_payment = Checkout_Go_Back_From_Payment(page)
    checkout_back_from_review =  Checkout_Go_Back_From_Review(page)
    shopping_cart = Open_Shopping_Cart_Page(page)



    # Case 1.1: Guest User + Premium Delivery (Same address without checkbox) + Amex Credit card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_login.test_checkout_as_guest_user()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 1.2: Guest User + Premium Delivery (Same address with checkbox) + Visa Credit card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_use_delivery_as_billing_address_checkbox()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 1.3: Guest User + Premium Delivery (different addresses) + Union Pay Credit card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()



    # Case 2.1: Guest User + Self Collect + Mastercard Credit card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()



    # Case 3.1  : Guest User + Collect by Other + Discover Credit card
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()



    # Case 4.1: Premium Delivery > Back to the Delivery tab from the Payment > Select Self Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 4.2: Premium Delivery > Back to the Delivery tab from the Payment > Select Someone else Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 4.3: Self Collect > Go Back to the Delivery tab from the Payment > Select Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_jcb_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 4.4: Self Collect > Go Back to the Delivery tab from the Payment > Select Someone else collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_jcb_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 4.5: Someone else Collect > Go Back to the Delivery tab from the Payment > Select Premium Delivery.
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 4.6: Someone else Collect > Go Back to the Delivery tab from the Payment > Select self collect.
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_back_from_payment.test_go_back_to_delivery_from_payment_page()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()


    # Case 5.1: Premium Delivery > Go Back to the Delivery tab from the Review > Select self collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    
    # Case 5.2: Premium Delivery > Go Back to the Delivery tab from the Review > Select Someone else collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 5.3: Self Collect > Go Back to the Delivery tab from the Review > Select Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_jcb_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 5.4: Self Collect > Go Back to the Delivery tab from the Review > Select Someone else Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()


    # Case 5.5: Someone else Collect > Go Back to the Delivery tab from the Review > Select Premium Delivery
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 5.6: Someone else Collect > Go Back to the Delivery tab from the Review > Select Self Collect
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_jcb_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_delivery_from_review_page()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

  # Case 6.1: Premium Delivery > Go Back to the Payment tab from the Review.
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_mastercard_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_payment_from_review_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 6.2: Self Collect > Go Back to the Payment tab from the Review.
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_payment_from_review_page()
    checkout_payment.test_enter_jcb_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 6.3: Someone else Collect > Go Back to the Payment tab from the Review.
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_someone_else_collect_in_store_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_back_from_review.test_go_back_to_payment_from_review_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()


    # Case 8.1: Premium Delivery to Collect in Store > Go Back to the Cart page from the Review page and Change delivery method.
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page() 
    checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_visa_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 8.2: Collect in store to Premium Delivery > Go Back to the Cart page from the Review page and Change delivery method.
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page() 
    checkout_back_from_review.test_go_back_to_shopping_cart_from_review_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_discover_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()    



    # Case 9.1: Premium Delivery to Collect in Store > Go Back to the Cart page from the Payment page and Change delivery method.
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_amex_credit_card_details()
    checkout_payment.test_enter_change_billing_name_details()
    checkout_payment.test_enter_change_billing_address_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()

    # Case 9.2: Collect in store to Premium Delivery > Go Back to the Cart page from the Payment page and Change delivery method.    
    checkout_pdp.test_checkout_spp_no_size_with_engraving()
    checkout_pdp.test_checkout_spp_no_size_without_engraving()
    checkout_pdp.test_secure_checkout_from_minicart()
    checkout_delivery.test_self_collect_in_store_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_back_from_payment.test_go_back_to_shopping_cart_from_payment_page()
    shopping_cart.test_continue_to_checkout_from_cart()
    checkout_delivery.test_premium_delivery_as_guest()
    checkout_delivery.test_continue_to_payment_from_delivery_page()
    checkout_payment.test_enter_union_pay_credit_card_details()
    checkout_payment.test_continue_to_review_from_payment_page()
    checkout_review.test_place_an_order_from_order_review_page()